---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-management
spec:
  description: Manage cluster resources
  sourceRepos:
    - https://github.com/samuelvl/ocp4-onboarding.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
