---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ocp4-examples
  namespace: argocd
spec:
  description: Deploy ocp4-examples
  sourceRepos:
    - https://github.com/samuelvl/ocp4-examples.git
  destinations:
    - namespace: frontend* # frontend-pre, frontend-dev, etc
      server: https://kubernetes.default.svc
    - namespace: bigdata* # bigdata-pre, bigdata-dev, etc
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
