= Onboarding

The project is the organizational unit for different OCP components.

- RBAC (roles and rolebindings).
- Traffic isolation (network policies).
- Resources management (resource quota and limit range).
- Configuration (config map and secret).

== Template

Default settings for a project can be inherited from a `+Template+`. When a project is created with the `+oc new-project+` command or from the web console, the default template is applied with the custom configuration.

NOTE: The default template will not be applied if the project is created using the `+Namespace+` object.

Create a new project `+Template+`.

[source,bash]
----
oc apply -f project-templates/example.yml
----

Set this template as the default one for new projects.

[source,bash]
----
oc patch project.config cluster \
    --type=merge \
    --patch \
    '{"spec":{"projectRequestTemplate":{"name":"example"}}}'
----

Create a new project to verify if the default resources are created.

[source,bash]
----
oc new-project onboarding-project-testing
oc get configmap example -n onboarding-project-testing -o jsonpath='{.data.text}{"\n"}'

oc create namespace onboarding-namespace-testing
oc get configmap -n onboarding-namespace-testing # Template is not applied
----

== Kustomize

Add a new base to `+kustomize/kustomization.yml+` file with the name of the namespace.

[source,yaml]
----
include::kustomize/kustomization.yml[]
----

Create a new namespace folder from skeleton example.

[source,bash]
----
# kustomize/namespaces/skeleton
# ├── kustomization.yml
# ├── namespace
# │   ├── kustomization.yml
# │   └── manifests
# │       └── example.yml
# └── argocd
#     └── application.yml
cp -r kustomize/namespaces/skeleton kustomize/namespaces/new-project
----

Substitute the following variables and add the additional manifests to the `+namespace+` folder.

.Skeleton variables
[#optional-id,cols="1,3",options="header"]
|===
| **Variable**            | **Example**
| {{ namespace_name }}    | example
| {{ repository_url }}    | https://github.com/org/example.git
| {{ repository_path }}   | openshift-app
| {{ repository_branch }} | main
| {{ argocd_project }}    | example-org
|===

[source,bash]
----
kustomize build kustomize | oc apply -f -
----

== ArgoCD

Configure an ArgoCD `+Application+` to synchronize the projects managed by Kustomize.

[source,bash]
----
include::argocd/apps/onboarding.yml[]

oc apply -f argocd/apps/onboarding.yml
----

Control in which namespace the repository code can be deployed.

[source,bash]
----
include::argocd/projects/ocp4-examples.yml[]

oc apply -f argocd/projects
----

Create a new repository `+ocp4-examples+` to verify if applications can be deployed in their corresponding namespaces.

[source,bash]
----
gh repo create ocp4-examples --public
git clone git@github.com:samuelvl/ocp4-examples.git
cp -r ocp4-examples-base/* ocp4-examples
cd ocp4-examples
git add . && git commit -am "Deploy applications using argocd" && git push
----

== References

- https://docs.openshift.com/container-platform/4.6/applications/projects/configuring-project-creation.html
- https://github.com/kubernetes-sigs/kustomize
