---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bigdata-orders
  namespace: argocd
spec:
  project: ocp4-examples
  source:
    repoURL: https://github.com/samuelvl/ocp4-examples.git
    path: bigdata-orders
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: bigdata-orders
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
