---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-cart
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/display-name: Frontend cart
    openshift.io/description: Frontend cart deployment
    openshift.io/requester: Kustomize
