---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onboarding
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://github.com/samuelvl/ocp4-onboarding.git
    path: kustomize
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
