---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-cart
  namespace: argocd
spec:
  project: ocp4-examples
  source:
    repoURL: https://github.com/samuelvl/ocp4-examples.git
    path: frontend-cart
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-cart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
