---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-cart
  namespace: argocd
spec:
  project: argocd-examples
  source:
    repoURL: https://github.com/samuelvl/argocd-examples.git
    path: frontend-cart-apps
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-cart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
