---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend-cart
bases:
  - ../../../base
resources:
  - manifests/namespace.yml
  - manifests/rbac.yml
  - manifests/quota.yml
